# Generated by Django 4.0.3 on 2022-06-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatterbot', '0018_text_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
